export const profile = {
  id: "aj159",
  name: "AJAZZ AJ159 / AJ159P",
  type: 102,
  driver: "compx",
  image: "assets/device/mouse_aj159.png",
  sensor: "PAW3395",
  maxDpi: 26000,
  modes: [
    { value: 0, desc: "USB", vid: "248A", pid: "5C2E", devId: "M620" },
    { value: 1, desc: "2.4G", vid: "248A", pid: "5C2F", devId: "M620" },
  ],
  keys: [
    { id: 201, keyValue: 0, direction: "right", x: 29.3, y: 29.7, defaultFunc: "left", lockedDefault: true },
    { id: 202, keyValue: 1, direction: "left", x: 70.4, y: 29.5, defaultFunc: "right" },
    { id: 203, keyValue: 2, direction: "bottom", x: 50.2, y: 16.5, defaultFunc: "middle" },
    { id: 204, keyValue: 4, direction: "right", x: 22.3, y: 40.9, defaultFunc: "forward" },
    { id: 205, keyValue: 3, direction: "right", x: 22, y: 52.6, defaultFunc: "backward" },
    { id: 206, keyValue: 5, direction: "left", x: 61.2, y: 54, defaultFunc: "dpi_loop" },
  ],
  dpiDefaults: [
    { value: 400, color: "#FF0000" },
    { value: 800, color: "#00FF00" },
    { value: 1200, color: "#0000FF" },
    { value: 1600, color: "#00FFFF" },
    { value: 2400, color: "#FFFF00" },
    { value: 3200, color: "#800080" },
  ],
  defaultDpiIndex: 1,
  reportRates: [125, 250, 500, 1000],
  defaultRateIndex: 3,
  lights: [
    { id: "flow", name: "Flowing light", enable: false },
    { id: "breathe", name: "Breathing", enable: true },
    { id: "solid", name: "Constant light", enable: true },
    { id: "neon", name: "Neon", enable: false },
    { id: "wave", name: "Colorful waves", enable: false },
    { id: "off", name: "Close", enable: true },
  ],
  defaultLight: "breathe",
};
